### ISSUE TITLE
Error executing hello-universe.sh

### ISSUE THREAD

**Issue by mfts** [teaxyz/demos#7]
MacOS Terminal thinks that `sh` is declared twice for some reason. 

Error message: 
```
{
  cwd: undefined,
  cmd: [
    "sh",
    "sh",
    "/Users/mfts/.tea/tea.xyz/var/www/https/raw.githubusercontent.com/2936f4482273b99bb46d6d6e2bce1d8fa98..."
  ],
  env: { LDFLAGS: "-Wl,-rpath,/Users/mfts/.tea", TEA_PREFIX: "/Users/mfts/.tea" }
}
```

Fixed by removing these lines:
https://github.com/teaxyz/demos/blob/64f2f92a649c78461b64eb192f1b60b8b650d603/hello-universe.sh#L5-L10

Steps to recreate:
1. Download script `tea https://github.com/teaxyz/demos/blob/main/hello-universe.sh` downloads package to `~/.tea/tea.xyz/var/www...`
2. Make executable `chmod +x ~/.tea/tea.xyz/var/www/https/raw.githubusercontent.com/.../hello-universe.sh`
3. Run script again `tea https://github.com/teaxyz/demos/blob/main/hello-universe.sh`

**Comment by mxcl** [comment]
oh ok, this is my bad (introduced with magic shebang code in 0.14.0). we don’t need the args now, but if the args are specified `tea` shouldn’t add more.

**Comment by mxcl** [comment]
tested and works with 0.14.2
